BALL_X_SPEED_AMP         = $6000
BALL_Y_SPEED_AMP         = $6001
BALL_Y                   = $0220
BALL_X                   = $0223
PLAYER_1_SPEED           = $6100
PLAYER_2_SPEED           = $6101
;JOYPAD_1_ADDR           = $4016
JOYPAD_1_DATA            = $0100
JOYPAD_2_DATA            = $0101
PLAYER_1_Y               = $0224
PLAYER_2_Y               = $0228
COLLISION_ADDR           = $0104
PLAYER_1_POINTS_DISPLAY  = $022D
PLAYER_2_POINTS_DISPLAY  = $0231
PLAYER_1_POINTS          = $7001
PLAYER_2_POINTS          = $7002
BALL_SPEED               = $700D
HIGHH                    = $700E
PLAYER_TURN              = $700F
PLAYING_Y                = $0107
;;;;;;;;;;;;;;           = $0103
PAUSE_TIMER              = $7200
TUNE_NOTE                = $7201
TUNE_BPM                 = $7202
TUNE_BEAT                = $7203
BAR_REPEAT               = $7204
BAR_COUNT                = $7205
NOTE_INDEX               = $7206
NOTE_PLAYER_TIMER        = $7207

APU_PULSE_1_COUNTER      = $7208
APU_PULSE_2_COUNTER      = $7209

ROW_COUNTER              = $20
TIME_COUNTER             = $21

TUNE_ADDR                = $83B7
;;;;;;;;;;;;;;
;>--------https://wiki.nesdev.com/w/index.php/APU-------<;
APU_PULSE_1              = $4000
APU_PULSE_1_DDLCVVVV     = $4000
APU_PULSE_1_EPPPNSSS     = $4001
APU_PULSE_1_TTTTTTTT     = $4002
APU_PULSE_1_LLLLLTTT     = $4003

APU_PULSE_2_DDLCVVVV     = $4004
APU_PULSE_2_EPPPNSSS     = $4005
APU_PULSE_2_TTTTTTTT     = $4006
APU_PULSE_2_LLLLLTTT     = $4007

APU_TRIANGLE_CRRRRRRR    = $4008
APU_TRIANGLE_________    = $4009
APU_TRIANGLE_TTTTTTTT    = $400A
APU_TRIANGLE_LLLLLTTT    = $400B

APU_NOISE___LCVVVV       = $400C
APU_NOISE_________       = $400D
APU_NOISE_L___PPPP       = $400E
APU_NOISE_LLLLL___       = $400F
;>------------------------------------------------------<;